
import { createClient } from '@supabase/supabase-js'
import { Database } from '../src/integrations/supabase/types'

const supabase = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!
)

const vehicles = [
  {
    plate: 'KIWICAR',
    make: 'Toyota',
    model: 'Camry',
    year: 2022,
    color: 'Silver',
    vin: '1234567890ABCDEFG',
    registration_status: 'Registered',
    registration_expiry: '2025-12-31',
    wof_status: 'Valid',
    wof_expiry: '2025-06-30',
    rego_status: 'Valid',
    rego_expiry: '2025-12-31',
    axles: 2,
    seats: 5,
    engine_size: '2.5L',
    power: '152kW',
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    body_style: 'Sedan',
    main_color: 'Silver',
    second_color: 'None',
    vehicle_type: 'Passenger Car/Van',
    vehicle_usage: 'Private',
    country_of_origin: 'Japan',
    gross_vehicle_mass: '2100kg',
    tare_weight: '1580kg',
    max_rated_towed_mass: '1600kg',
    road_user_charges_licence: 'N/A',
    compliance_plate: 'ABC12345',
    safety_rating: '5-star ANCAP',
    airbag_count: 8,
    has_abs: true,
    has_esc: true,
    active_recalls: { "recalls": ["Takata airbag recall"] },
    theft_alert_status: 'No stolen alerts reported',
    number_of_owners: 2,
    first_registration_date: '2022-01-15',
    import_date: '2022-01-10',
    previous_country: 'Japan',
    lien_information: 'No security interest recorded',
    last_odometer_reading: '45,000km at 2024-05-20',
    write_off_status: 'Not written off',
    market_valuation: '$30,000 - $35,000',
    replacement_cost: '$40,000',
    modification_approvals: { "approvals": ["Certified towbar installation"] },
    noise_level_compliance: 'Compliant',
    commercial_restrictions: 'None'
  },
  {
    plate: 'TEST1234',
    make: 'Ford',
    model: 'Ranger',
    year: 2020,
    color: 'Blue',
    vin: 'FEDCBA0987654321',
    registration_status: 'Registered',
    registration_expiry: '2024-11-30',
    wof_status: 'Valid',
    wof_expiry: '2024-10-15',
    rego_status: 'Valid',
    rego_expiry: '2024-11-30',
    axles: 2,
    seats: 5,
    engine_size: '3.2L',
    power: '147kW',
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    body_style: 'Ute',
    main_color: 'Blue',
    second_color: 'None',
    vehicle_type: 'Goods Van/Ute',
    vehicle_usage: 'Commercial',
    country_of_origin: 'Thailand',
    gross_vehicle_mass: '3200kg',
    tare_weight: '2150kg',
    max_rated_towed_mass: '3500kg',
    road_user_charges_licence: 'Active',
    compliance_plate: 'XYZ98765',
    safety_rating: '5-star ANCAP',
    airbag_count: 6,
    has_abs: true,
    has_esc: true,
    active_recalls: { "recalls": [] },
    theft_alert_status: 'No stolen alerts reported',
    number_of_owners: 1,
    first_registration_date: '2020-03-20',
    import_date: null,
    previous_country: null,
    lien_information: 'Security interest held by XYZ Finance',
    last_odometer_reading: '80,000km at 2024-04-10',
    write_off_status: 'Not written off',
    market_valuation: '$45,000 - $50,000',
    replacement_cost: '$55,000',
    modification_approvals: { "approvals": ["Canopy fitted"] },
    noise_level_compliance: 'Compliant',
    commercial_restrictions: 'None'
  },
  {
    plate: 'NZMADE',
    make: 'Subaru',
    model: 'Outback',
    year: 2023,
    color: 'Green',
    vin: 'SUBARU1234567890',
    registration_status: 'Registered',
    registration_expiry: '2026-01-31',
    wof_status: 'Valid',
    wof_expiry: '2026-01-31',
    rego_status: 'Valid',
    rego_expiry: '2026-01-31',
    axles: 2,
    seats: 5,
    engine_size: '2.5L',
    power: '138kW',
    fuel_type: 'Petrol',
    transmission: 'CVT',
    body_style: 'Station Wagon',
    main_color: 'Green',
    second_color: 'None',
    vehicle_type: 'Passenger Car/Van',
    vehicle_usage: 'Private',
    country_of_origin: 'Japan',
    gross_vehicle_mass: '2100kg',
    tare_weight: '1650kg',
    max_rated_towed_mass: '2000kg',
    road_user_charges_licence: 'N/A',
    compliance_plate: 'SUB12345',
    safety_rating: '5-star ANCAP',
    airbag_count: 7,
    has_abs: true,
    has_esc: true,
    active_recalls: { "recalls": [] },
    theft_alert_status: 'No stolen alerts reported',
    number_of_owners: 1,
    first_registration_date: '2023-02-01',
    import_date: null,
    previous_country: null,
    lien_information: 'No security interest recorded',
    last_odometer_reading: '15,000km at 2024-01-30',
    write_off_status: 'Not written off',
    market_valuation: '$50,000 - $55,000',
    replacement_cost: '$60,000',
    modification_approvals: { "approvals": [] },
    noise_level_compliance: 'Compliant',
    commercial_restrictions: 'None'
  }
];

async function seedData() {
  for (const vehicle of vehicles) {
    const { data, error } = await supabase.from('vehicles').insert(vehicle);
    if (error) {
      console.error('Error inserting vehicle', vehicle.plate, error);
    } else {
      console.log('Inserted vehicle', vehicle.plate, data);
    }
  }
}

seedData();
