
import { createClient } from '@supabase/supabase-js';
import { Database } from '../src/integrations/supabase/types';

const supabase = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!
);

async function seed() {
  const { data, error } = await supabase
    .from('vehicles')
    .insert([
      {
        plate: '1AB2CD',
        make: 'Toyota',
        model: 'Camry',
        variant: 'Hybrid',
        year: 2022,
        color: 'Silver',
        vin: '1234567890ABCDEFG',
        chassis_number: 'ABC123456789',
        country_of_origin: 'Japan',
        vehicle_type: 'Sedan',
        body_style: 'Sedan',
        number_of_doors: 4,
        transmission: 'Automatic',
        drive_type: 'FWD',
        engine_size: '2.5L',
        fuel_type: 'Hybrid',
        number_of_cylinders: 4,
        power_output: '155kW',
        torque: '221Nm',
        emission_standard: 'Euro 6',
        fuel_consumption: '4.2L/100km',
        co2_emissions: '96g/km',
        max_speed: '180km/h',
        gross_vehicle_mass: '2100kg',
        tare_weight: '1580kg',
        registration_status: 'Active',
        registration_expiry: '2025-01-15',
        wof_status: 'Active',
        wof_expiry: '2025-01-15',
        cof_status: null,
        ruc_status: 'N/A',
        import_compliance_date: '2022-01-15',
        compliance_plate: 'Yes',
        safety_rating: '5 Star',
        airbag_count: 8,
        has_abs: true,
        has_esc: true,
        active_recalls: '[]',
        theft_alert_status: 'Secure',
        number_of_owners: 1,
        first_registration_date: '2022-01-15',
        import_date: '2022-01-01',
        previous_country: 'Japan',
        lien_information: 'None',
        last_odometer_reading: '15,000 km',
        write_off_status: 'None',
        market_valuation: '$35,000',
        replacement_cost: '$40,000',
        modification_approvals: '[]',
        noise_level_compliance: 'Yes',
        commercial_restrictions: 'None',
      },
      {
        plate: '3DE4FG',
        make: 'Ford',
        model: 'Ranger',
        variant: 'XLT',
        year: 2021,
        color: 'Blue',
        vin: '0987654321HGFEDCBA',
        chassis_number: 'DEF0987654321',
        country_of_origin: 'Thailand',
        vehicle_type: 'Ute',
        body_style: 'Double Cab',
        number_of_doors: 4,
        transmission: 'Automatic',
        drive_type: '4WD',
        engine_size: '3.2L',
        fuel_type: 'Diesel',
        number_of_cylinders: 5,
        power_output: '147kW',
        torque: '470Nm',
        emission_standard: 'Euro 5',
        fuel_consumption: '8.9L/100km',
        co2_emissions: '234g/km',
        max_speed: '175km/h',
        gross_vehicle_mass: '3200kg',
        tare_weight: '2200kg',
        registration_status: 'Active',
        registration_expiry: '2024-11-20',
        wof_status: 'Active',
        wof_expiry: '2024-11-20',
        cof_status: null,
        ruc_status: 'Up to date',
        import_compliance_date: '2021-03-10',
        compliance_plate: 'Yes',
        safety_rating: '5 Star',
        airbag_count: 6,
        has_abs: true,
        has_esc: true,
        active_recalls: '[]',
        theft_alert_status: 'Secure',
        number_of_owners: 2,
        first_registration_date: '2021-03-10',
        import_date: '2021-02-15',
        previous_country: 'Australia',
        lien_information: 'None',
        last_odometer_reading: '45,000 km',
        write_off_status: 'None',
        market_valuation: '$55,000',
        replacement_cost: '$60,000',
        modification_approvals: '[]',
        noise_level_compliance: 'Yes',
        commercial_restrictions: 'None',
      },
    ]);

  if (error) {
    console.error('Error seeding data:', error);
  } else {
    console.log('Successfully seeded data:', data);
  }
}

seed();
